// ADD SYSTEM SO USER IS NOTIFIED OF SUCCESSFUL REGISTER OR REDIRECTED TO LOGIN.



//TRACK EXERCISE PAGE SHOULD GIVE THE USER THE OPTION TO:
    // CREATE ROUTINE
    // LOOK AT ROUTINES
    // LOOK AT ACTIVITIES

//GET POST REQUESTS FOR ACTIVITIES UP