// ADD SYSTEM SO USER IS NOTIFIED OF SUCCESSFUL REGISTER OR REDIRECTED TO LOGIN.
// ADD SYSTEM TO NOTIFY USER WHEN ROUTINES/ACTIVITIES ARE CREATED/DELETED/UPDATED
// NEED TO BE ABLE TO UPDATE ITEMS



//TRACK EXERCISE PAGE SHOULD GIVE THE USER THE OPTION TO:
    // CREATE ROUTINE
    // LOOK AT ROUTINES
    // LOOK AT ACTIVITIES


    // ADD LOGO TO TAB NEXT TO TITLE OF PAGE