// ADD SYSTEM SO USER IS NOTIFIED OF SUCCESSFUL REGISTER OR REDIRECTED TO LOGIN.
// ADD SYSTEM TO NOTIFY USER WHEN ROUTINES/ACTIVITIES ARE CREATED/DELETED/UPDATED
// NEED TO BE ABLE TO UPDATE ITEMS

//ADD SEARCH MECHANISM ON ROUTINSE AND ACTIVITIES THAT PRE-FILLS 

//TRACK EXERCISE PAGE SHOULD GIVE THE USER THE OPTION TO:
    // CREATE ROUTINE
    // LOOK AT ROUTINES
    // LOOK AT ACTIVITIES


    // ADD LOGO TO TAB NEXT TO TITLE OF PAGE


    //FOR UPDATE BUTTONS ->
        // HAVE A PIECE OF STATE THAT DEFAULTS TO FALSE.
            //ON CLICK OF EDIT BUTTON, THIS STATE TOGGLES.
                //ON TRUE, THE NAME and DESCRIPTION BECOME INPUTS THAT THE USER CAN MODIFY
                    // THE EDIT BUTTON CONTINUES TO TOGGLE AND A NEW SUBMIT BUTTON WILL EXECUTE PATCH API CALL